data<-read.csv("~/AI_Omics_Internship_2025/patient_info.csv")
View(data)
str(data)
data$age_fac<- as.factor(data$age)
str(data)
data$gender_fac<- as.factor(data$gender)
str(data)
data$gender_num<- ifelse(data$gender_fac == "Female",1,0)
class(data$gender_num)
data$gender_num<-as.factor(data$gender_num)
print(data$gender)
data$diagnosis_fac<- as.factor(data$diagnosis)
str(data)
data$diagnosis_num<-ifelse(data$diagnosis_fac == "Cancer", 1,0)
class(data$diagnosis_num)
data$smoker_fac<- as.factor(data$smoker)
str(data)
data$smoker_num<- ifelse(data$smoker_fac == "Yes",1,0)
class(data$smoker_num)
